stages:
  - Base containers
  - Derived containers

include:
  - local: /gitlab-ci/build/docker.yml

#
# Templates
#
.containers:build:
  extends: .docker:build
  variables:
    DOCKER_BUILD_CONTEXT_DIR: containers/$container
    DOCKER_IMAGE_REPO: $CI_REGISTRY_IMAGE/$container
    DOCKER_IMAGE_TAGS: >-
      $CI_COMMIT_SHA
      $CI_COMMIT_REF_SLUG
      $CI_COMMIT_TAG
      latest
    DOCKER_BUILD_CACHE_IMAGES: >-
      $CI_REGISTRY_IMAGE/$container:$CI_COMMIT_BEFORE_SHA
      $CI_REGISTRY_IMAGE/$container:$CI_COMMIT_REF_SLUG
      $CI_REGISTRY_IMAGE/$container:latest
    DOCKER_BUILD_EXTRA_ARGS: >-
      --build-arg BASE_IMAGE=fedora:31

#
# Bases
#
containers:helm:
  stage: Base containers
  extends: .containers:build
  variables:
    container: helm
  only:
    changes:
      - containers/helm/**/*

containers:kubectl:
  stage: Base containers
  extends: .containers:build
  variables:
    container: kubectl
  only:
    changes:
      - containers/kubectl/**/*

#
# Derived
#
containers:k8s-tools-container:
  stage: Derived containers
  extends: .containers:build
  variables:
    container: k8s-tools-container
    DOCKER_BUILD_EXTRA_ARGS: >-
      --build-arg BASE_IMAGE=fedora:31
      --build-arg HELM_IMAGE=$CI_REGISTRY_IMAGE/helm:latest
      --build-arg KUBECTL_IMAGE=$CI_REGISTRY_IMAGE/kubectl:latest
  only:
    changes:
      - containers/helm/**/*
      - containers/kubectl/**/*
      - containers/k8s-tools-container/**/*
